import type { Metadata } from "next";
import { Iceland, Roboto } from "next/font/google";
import "./globals.css";
import Provider from "./_trpc/Provider";
import { Toaster } from "@/components/ui/sonner";
import { FloatingNavbar } from "@/components/navbar/floating-navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const fontNunito = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-nunito",
});

const iceland = Iceland({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-iceland",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased relative  ${fontNunito.variable} ${iceland.variable}  flex h-full w-full  items-center bg-dark-100`}
      >
        <Provider>
          {children}
          <FloatingNavbar />
          <Toaster richColors position="bottom-right" />
        </Provider>
      </body>
    </html>
  );
}
